#Version : 0.0.1
#static web
FROM ubuntu:14.04
MAINTAINER Gavin "gavin2lee@163.com"
RUN apt-get update && apt-get install -y nginx
RUN echo 'Hi,I am in your container' \
    >/usr/share/nginx/html/index.html
EXPOSE 80
